### PR TITLE
Improve code coverage by updating tests

### PR DESCRIPTION
**Pull request by hardikj**

### CODE REVIEW

**Comment by hardikj** [comment]
do we really need this peace of code? https://coveralls.io/files/410949538#L91

**Comment by d00rman** [comment]
Great work for the GET/PUT on non-existent tables, @hardikj ! Speaking of that, it makes me think. Doing a get or a put on such tables shouldn't return a 500 status code. It's actually a client (4xx) 'problem'.
BTW, is there a reason for renaming simpleTable into simple-table?

**Comment by hardikj** [comment]
> Doing a get or a put on such tables shouldn't return a 500 status code. It's actually a client (4xx) 'problem'.

Ah! very well spotted, but I think its restbase that convert those 500 to 4xx since the response first goes through restbase before going to client.

>  is there a reason for renaming simpleTable into simple-table
Yes, To cover this regex case here, https://coveralls.io/files/410978712#L84

**Comment by d00rman** [comment]
> Ah! very well spotted, but I think its restbase that convert those 500 to 4xx since the response first goes through restbase before going to client.
Good point. Besides, restbase should be the only entity accessing the storage directly, so we may assume here that it is going to handle that case well. Well, let's sleep on it :)
> is there a reason for renaming simpleTable into simple-table
> Yes, To cover this regex case here, https://coveralls.io/files/410978712#L84
Ah, right, good find!

**Comment by d00rman** [comment]
> do we really need this peace of code? https://coveralls.io/files/410949538#L91

Yes, we do. It allows us to get the schema info in the same format as the cached version.

**Comment by hardikj** [comment]
>> do we really need this peace of code? https://coveralls.io/files/410949538#L91

> Yes, we do. It allows us to get the schema info in the same format as the cached version.

Reason, I asked that was that we are never reaching the then statement, I am not sure why?

**Comment by gwicke** [comment]
@hardikj, great work!

**Pull request merged**
